services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - users_db
      - listings_db
    environment:
      - USERS_DB_HOST=${USERS_DB_HOST}
      - USERS_DB_PORT=${USERS_DB_PORT}
      - LISTINGS_DB_HOST=${LISTINGS_DB_HOST}
      - LISTINGS_DB_PORT=${LISTINGS_DB_PORT}

  users_db:
    image: postgres:14
    volumes:
      - users_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${USERS_DB_NAME}
      - POSTGRES_USER=${USERS_DB_USER}
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}

  listings_db:
    image: postgres:14
    volumes:
      - listings_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${LISTINGS_DB_NAME}
      - POSTGRES_USER=${LISTINGS_DB_USER}
      - POSTGRES_PASSWORD=${LISTINGS_DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
  mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1    

 

volumes:
  users_postgres_data:
  listings_postgres_data:
