# Generated by Django 3.2.6 on 2026-04-05 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.CharField(default='published', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('realtor', models.CharField(max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('zipcode', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(db_index=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=255)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Multi-Family', 'Multi Family'), ('Land', 'Land')], default='House', max_length=255)),
                ('main_photo', models.ImageField(upload_to='listing_photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='listing_photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='listing_photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='listing_photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'state', 'zipcode'], name='listing_lis_city_d550f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
    ]
