# Generated by Django 3.2.6 on 2026-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('drafts', 'Drafts'), ('published', 'Published')], db_index=True, default='drafts', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
